stages:
  - build
  - analysis
  - security
  - dockerize
  - scan

# Define the CI/CD pipeline jobs
jobs:
  - job: Build
    displayName: 'Build stage'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Building the Java code...'
        displayName: 'Building the code'

  - job: Software_Component_Analysis
    displayName: 'Software Component Analysis'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Performing Software Component Analysis...'
        displayName: 'Software Component Analysis'

  - job: Static_Analysis
    displayName: 'Static Analysis (SAST)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Running Static Analysis (SAST)...'
        displayName: 'Static Analysis (SAST)'

  - job: License_Compliance
    displayName: 'License Compliance'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Checking License Compliance...'
        displayName: 'License Compliance'

  - job: Build_Docker_Image
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Building Docker image...'
        displayName: 'Building Docker Image'

  - job: Container_Image_Scan
    displayName: 'Container Image Scan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Scanning Container Image for vulnerabilities...'
        displayName: 'Container Image Scan'

  - job: DAST_Scan
    displayName: 'DAST Scan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo 'Running Dynamic Application Security Testing (DAST)...'
        displayName: 'DAST Scan'
