# Define the stages of the pipeline
stages:
  - build
  - test
  - scan
  - deploy

# Define the jobs for each stage
build:
  stage: build
  image: maven:latest
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:latest
  script:
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/*.xml

scan:
  stage: scan
  image: veracode/veracode-pipeline-scan:latest
  script:
    - veracode -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY -f target/*.jar -action sca
    - veracode -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY -f target/*.jar -action static
    - veracode -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY -f target/*.jar -action license
    - veracode -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY -f target/*.jar -action dast -url $APP_URL
  artifacts:
    paths:
      - veracode-results/*.json

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker scan $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE
    - docker run -d -p 8080:8080 $DOCKER_IMAGE

# Trigger the pipeline when changes are pushed to the master branch
# Run this pipeline only when there are changes in the master branch
# Triggered on commit to the master branch
only:
  - master
