name: Code Scanning and Image Scanning

on:
  workflow_dispatch:
  workflow_call:

jobs:
  scan-code-and-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Detect Language
        id: detect-language
        run: |
          # Use a script to detect the programming language and store it in an environment variable.
          # Replace this with your language detection logic.
          echo "DetectedLanguage=python" >> $GITHUB_ENV
        shell: bash

      - name: Code Scanning
        if: steps.detect-language.outputs.DetectedLanguage == 'python'
        run: |
          # Perform code scanning for Python (replace with your code scanning command).
          echo "Performing code scanning for Python..."
          # Example: Run semgrep for Python
          semgrep --config=my_rules.yaml --json -o semgrep_results.json .
        shell: bash

      - name: CodeQL Analysis
        if: steps.detect-language.outputs.DetectedLanguage == 'java'
        run: |
          # Perform CodeQL analysis for Java (replace with your CodeQL analysis command).
          echo "Performing CodeQL analysis for Java..."
          # Example: Run CodeQL for Java
          codeql analyze --sarif=codeql_results.sarif
        shell: bash

      - name: Docker Image Scanning
        if: steps.detect-language.outputs.DetectedLanguage == 'dockerfile'
        run: |
          # Perform Docker image scanning for Dockerfile (replace with your image scanning command).
          echo "Performing Docker image scanning for Dockerfile..."
          # Example: Run trivy for Docker image scanning
          trivy --input your-image.tar.gz --format json -o image_scan_results.json
        shell: bash

      - name: Upload Reports
        run: |
          # Upload the generated reports to GitHub as artifacts.
          echo "Uploading code scanning report..."
          mv semgrep_results.json code_scan_results.json
          echo "Uploading Docker image scanning report..."
          mv image_scan_results.json docker_image_scan_results.json
          echo "Uploading CodeQL analysis report..."
          mv codeql_results.sarif codeql_analysis_report.sarif
        shell: bash

      - name: Archive Reports
        uses: actions/upload-artifact@v2
        with:
          name: code-scanning-reports
          path: |
            code_scan_results.json
            docker_image_scan_results.json
            codeql_analysis_report.sarif
