name: Code Scanning and Static Analysis

on:
  workflow_dispatch:
  workflow_call:

jobs:
  scan-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: JavaScript Analysis (Next.js, Angular, React.js)
        if: ${{ contains(github.event.head_commit.added, 'package.json') || contains(github.event.head_commit.modified, 'package.json') }}
        run: |
          # Perform static analysis for JavaScript using semgrep
          echo "Performing JavaScript analysis..."
          semgrep --config=javascript_rules.yaml --json -o javascript_results.json .
        shell: bash

      - name: C# Analysis
        if: ${{ contains(github.event.head_commit.added, '*.cs') || contains(github.event.head_commit.modified, '*.cs') }}
        run: |
          # Perform static analysis for C# using your preferred tool
          echo "Performing C# analysis..."
          # Replace with your C# analysis command
        shell: bash

      - name: Dart Analysis
        if: ${{ contains(github.event.head_commit.added, '*.dart') || contains(github.event.head_commit.modified, '*.dart') }}
        run: |
          # Perform static analysis for Dart using your preferred tool
          echo "Performing Dart analysis..."
          # Replace with your Dart analysis command
        shell: bash

      - name: Java Analysis
        if: ${{ contains(github.event.head_commit.added, '*.java') || contains(github.event.head_commit.modified, '*.java') }}
        run: |
          # Perform static analysis for Java using CodeQL
          echo "Performing Java analysis..."
          # Replace with your Java CodeQL analysis command
        shell: bash

      - name: Upload Reports
        run: |
          # Rename the generated reports
          mv javascript_results.json javascript_analysis_results.json
          # You can similarly rename other reports here if needed
        shell: bash

      - name: Archive Reports
        uses: actions/upload-artifact@v2
        with:
          name: code-analysis-reports
          path: |
            javascript_analysis_results.json
            # Add other renamed reports here
