name: Code Scanning

on:
  workflow_dispatch:
  workflow_call:

jobs:
  scan-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: JavaScript Frameworks Static Analysis
        if: contains(github.event.head_commit.modified, 'js/') || contains(github.event.head_commit.modified, 'jsx/')
        run: |
          # Perform static analysis for JavaScript frameworks (Next.js, Angular, React.js)
          echo "Performing static analysis for JavaScript frameworks..."
          # Replace the command with the appropriate static analysis tool for JavaScript projects
          # Example: Run semgrep for JavaScript
          semgrep --config=my_rules.yaml --json -o js_static_analysis_results.json .
        shell: bash

      - name: C# Static Analysis
        if: contains(github.event.head_commit.modified, 'cs/')
        run: |
          # Perform static analysis for C#
          echo "Performing static analysis for C#..."
          # Replace the command with the appropriate static analysis tool for C# projects
          # Example: Run semgrep for C#
          semgrep --config=my_rules.yaml --json -o cs_static_analysis_results.json .
        shell: bash

      - name: Java Static Analysis
        if: contains(github.event.head_commit.modified, 'java/') || contains(github.event.head_commit.modified, 'src/')
        run: |
          # Perform static analysis for Java
          echo "Performing static analysis for Java..."
          # Replace the command with the appropriate static analysis tool for Java projects
          # Example: Run FindBugs or PMD for Java
          # Example: Run Checkstyle for Java
          # Example: Run CodeQL for Java
          # Replace with the actual command for Java static analysis
        shell: bash

      - name: Dart Static Analysis
        if: contains(github.event.head_commit.modified, 'dart/')
        run: |
          # Perform static analysis for Dart
          echo "Performing static analysis for Dart..."
          # Replace the command with the appropriate static analysis tool for Dart projects
          # Example: Run dartanalyzer for Dart
          dartanalyzer .
        shell: bash

      - name: Upload Reports
        run: |
          # Rename and upload the generated reports
          mv js_static_analysis_results.json javascript_static_analysis.json
          mv cs_static_analysis_results.json csharp_static_analysis.json
          # Upload the reports as artifacts
          echo "Uploading analysis reports..."
        shell: bash

      - name: Archive Reports
        uses: actions/upload-artifact@v2
        with:
          name: code-scanning-reports
          path: |
            javascript_static_analysis.json
            csharp_static_analysis.json
